version: '3'

services:
  db-test:
    extends:
      file: ./docker-compose-base.yml
      service: db-base
  api-test:
    extends:
      file: ./docker-compose-base.yml
      service: api-base
    depends_on:
      db-test:
        condition: service_healthy
    command: test
  frontend-test:
    extends:
      file: ./docker-compose-base.yml
      service: ui-base
    environment:
      TESTING: "true"
    command: test