networks:
  # docker network create ${NETWORK_NAME}
  internal:
    external: true
    name: ${NETWORK_NAME}

volumes:
  # docker volume create ${DB_VOLUME}
  database_data:
    external: true
    name: ${DB_VOLUME}

services:
  db:
    extends:
      file: ./docker-compose-base.yml
      service: db-base
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - internal

  api:
    extends:
      file: ./docker-compose-base.yml
      service: api-base
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal

  ui:
    extends:
      file: ./docker-compose-base.yml
      service: ui-base
    networks:
      - internal
