version: '2.1'

services:
  db-test:
    extends:
      file: ./docker-compose-base.yml
      service: db-base
  django-test:
    extends:
      file: ./docker-compose-base.yml
      service: django-base
    depends_on:
      db-test:
        condition: service_healthy
    command: test
  frontend-test:
    extends:
      file: ./docker-compose-base.yml
      service: frontend-base
    environment:
      TESTING: "true"
    command: test